nuxtlabs/docus

app/router.options.ts, assets/css/main.css, components/docs/DocsPageContent.vue, components/docs/DocsTocLinks.vue, nuxt.config.ts
=> fix: click on heading and toc

assets/css/main.css, plugins/scrollbars.client.ts
=> feat: better scrollbars

composables/useScrollspy.ts
This fixes #700 by adding deep watch option in `useScrollspy.ts`:
from 
```ts
watch(visibleHeadings, (val, oldVal) => {
if (val.length === 0) { activeHeadings.value = oldVal } else { activeHeadings.value = val }
})
```
to 
```ts
watch(visibleHeadings, (val, oldVal) => {
if (val.length === 0) { activeHeadings.value = oldVal } else { activeHeadings.value = val }
}, { deep: true })
```
`useScrollspy.ts` 
While visibleHeadings were correctly updated when it came into a viewport (by chekcing if `entry.isIntersecting` using `IntersectionObserver` API), the watch function below did not updated activeHeadings in some circumstances (like when there were no activeHeadings in a viewport)
I tried adding deep option to the watch function and it fixed the problem (might be bad for performance?) …
=> fix: toc correctly reflects headings in a viewport

.docs/content/1.introduction/4.configuration.md
When 'icons' was renamed to 'iconLinks' here https://github.com/nuxt-themes/docus/commit/be04cc9d6dcd8a769029bdd295152e11a29f6755 the example Complete app.config.ts configuration wasn't updated.
=> Update 'icons' key in Complete app.config.ts example to 'iconLinks'

components/app/AppHeaderDialog.vue
`components/app/AppHeaderDialog.vue` component uses `header.exclude` to filter the navigation to display aside on mobile devices, which is actually aside but filtering with `header.exclude` causes filtering aside links
=> fix: use aside.exclude for mobile aside

.docs/content/0.index.md, .docs/content/1.introduction/1.getting-started.md, .docs/content/2.api/1.components.md
Otherwise last-used and possibly outdated version will be used.
=> docs: force latest version of nuxi

.docs/content/1.introduction/4.configuration.md
=> docs: add `textLinks` to configuration

components/docs/DocsAsideTree.vue
If you set the following in a _dir.yml the dir should be collapsed (or not) according to your choice.
```
aside:
collapsed: true/false
```
This way, you can fine-tune the collapsed state of each dir in the aside tree.
Resolves #743
=> feat: collapsed state fine-tuning 

.docs/content/1.introduction/4.configuration.md
=> docs: update definitions of configuration

components/app/AppHeader.vue, components/app/AppHeaderDialog.vue
=> fix: overflow social icons in AppHeaderDialog

app.config.ts
=> fix: remove socials default key to enable sorting for end user

components/docs/DocsPrevNext.vue
Fixes centring when there's no `directory`.
=> fix: remove empty directory span

components/docs/DocsTocLinks.vue
This is for when the TOC is rendered on a small device.
Without this code, only first level links close the TOC when clicked.
=> fix: Allow children links in toc to close the toc

components/docs/DocsAsideTree.vue
The line before the PR was not working when `aside.collapsed` was set to `false`, because the `if` statement was evaluated to `false`. I don't know if it's clean, but it works.
=> Fine tuning collapsed state

assets/css/main.css, tokens.config.ts
Makes Elements and Typography improvements much easier.
To fully preview it updates for Elements/Typography also needed (they are WIP).
Note: This should be moved to `tokens` asap.
=> feat: more flexible color palette

package.json
Fixing the warning from yarn run build:
```
miguelgargallo@host HOME p/docus-docs-starter (main)
$ yarn run build
yarn run v1.22.19
warning package.json: No license field
$ nuxi build .docs/
Nuxi 3.3.3                                                                  12:17:55
Nuxt 3.3.3 with Nitro 2.3.3                                                 12:17:55
```
=> Update package.json "License" added, fixed

README.md
=> docs: fix contributing

.docs/content/1.introduction/4.configuration.md, components/app/AppFooter.vue
=> feat: support rel in footer

README.md
In order to preview change using the command `npm run dev`, we need to extend local Docus.
=> docs: update contributing in readme

nuxt.schema.ts
Based on [AppHeaderLogo.vue](https://github.com/nuxt-themes/docus/blob/main/components/app/AppHeaderLogo.vue#L14-L35), you can set either a boolean, string or object for the logo. 
Currently, the generated type is only boolean, which breaks the type checking if you want to set a component (string) or the dark/light logo image URLs (object with strings).
This PR fixes this by setting the appropiate types. I have tested in the playground and works as expected. 
NOTE: I'm not sure what to do with `studioInput`. Does it break in Studio if you don't use a boolean?
=> fix(schema): extend logo types

components/docs/EditOnLink.vue, nuxt.schema.ts
Hi there 👋 
The purpose of this PR is to allow the `EditOnLink` and future components to work with Github Enterprise URLs.
_I've edited the component to show the URL just for the screenshot._
Thank you for the amazing work 🚀
=> feat: added Github baseURL to allow Enterprise URL

.starters/default/app.config.ts, .starters/default/content/1.introduction/4.configuration.md, components/app/AppSocialIcons.vue
Hi there 👋 
This PR is to be able to enable the users to set a full URL in social icons. For example:
```js
socials: {
github: "https://git.company.com",
},
```
Thank you very much for the incredible work! 🚀
=> fix: allow social icons to be a full URL

components/app/AppSearch.vue
Fixes #949
At the moment new docus projects are breaking when you deploy, the reason is because we are feeding `useFuse` a string instead of an array.
You can see the root of the error here: https://github.com/krisk/Fuse/blob/f507e9f19ff022c13e4517ecff3e7a72ee2688ee/src/tools/FuseIndex.js#L38-L47
The `$fetch` to `/api/search` is not parsing the array, adding `{ parseResponse: JSON.parse }` fixes this issue.
---
Steps to reproduce error on a brand new project:
```bash
npx nuxi@latest init docs -t themes/docus 
cd docs
npm install
npm run build
node .output/server/index.mjs
```
=> fix: fuse expects array not string

app.config.ts, components/app/AppSearch.vue, layouts/page.vue, nuxt.config.ts, pnpm-lock.yaml, server/routes/opensearch.xml.ts
This PR includes two parts:
1. Detection for url param `q`. If detected, open search page automatically.
2. Add `opensearch.xml` generation. The link is added to head of each page. The url is configured via `opensearch.url` in AppConfig.
=> feat: add opensearch support

components/app/AppSearch.vue
Resolves: https://github.com/nuxt-themes/docus/issues/996
Nuxt 3.8.0 changed typescript defaults to use explicit type imports. This PR makes docus ready for this change
=> fix: separate type imports

.starters/default/content/1.introduction/3.writing-pages.md
Fix for minor typo: "page" not "pages" on 3.writing-pages.md
=> docs: minor typo

docs/content/3.essentials/3.components.md
I found an example of both tabs being called "Preview" instead of one being "Code".
As the content had not, in fact, been duplicated, I simply corrected the label - amending both the text and the icon.
=> docs: fix erroneous labelling of code as preview

docs/content/en/1.getting-started/6.migration.md
Move the `.` where it belongs.
=> chore: get-started typo
